### ISSUE TITLE
Add Esperanto 

### ISSUE THREAD

**Issue by wh2bg** [Kr0oked/Compass#16]

**Comment by Kr0oked** [comment]
Hello, unfortunately I can't translate the app into esperanto myself. But if you are able to speak esperanto you are welcome to provide an appropriate translation. For this you have to provide translated versions for these files: 

https://github.com/Kr0oked/Compass/blob/master/app/src/main/res/values/strings.xml 
https://github.com/Kr0oked/Compass/blob/master/fastlane/metadata/android/en-US/title.txt 
https://github.com/Kr0oked/Compass/blob/master/fastlane/metadata/android/en-US/short_description.txt
https://github.com/Kr0oked/Compass/blob/master/fastlane/metadata/android/en-US/full_description.txt

If you are familiar with GIT you can create a pull request. Otherwise you can send me the translated files via Email or write the content as chat messages here.

Regards

**Comment by OmlineEditor** [comment]
the program language is taken from the android system settings. I have not seen that there was an Esperanto language in the system. how do I enable this language?

**Comment by Kr0oked** [comment]
Since Esperanto can not be used as a system language in Android there is no point in implementing a translation in this app.

**Comment by inson1** [comment]
@OmlineEditor I created issue for it #54

**Comment by inson1** [comment]
@Kr0oked If you agree with my issue #54, then maybe its time to reopen this issue

**Comment by inson1** [comment]
@Kr0oked If you can switch languages, why not add esperanto?

**Comment by Kr0oked** [comment]
If somebod is willing to provide translations for esperanto I will of cause include them in the application. But still I am not aware of any device that allows the user to select esperanto as locale. And I don't want to add an additional setting in the app. If possible the app should not "fight" with the system settings.
