### ISSUE TITLE
update to 1.5 cause trouble to the app

### ISSUE THREAD

**Issue by MacAlan-72** [Kr0oked/Compass#18]
Hello.

As an user of F-Droid, i have accepted the update 1.5 since that, the app don't work, displaying the error "sensor not available". I have uninstall the 1.5 version to come back to 1.4, the error is still here.

I am disappointed the app have worked 2 days and feels useful for me.

**Comment by Kr0oked** [comment]
Hello,
I'm sorry the app does not work for you. It is strange that the app once worked on your device on now displays this error. This error indicates that the app does not get access to the required sensor. But unfortunately I cannot tell why your system fails or refuses to provide this sensor.

**Comment by MacAlan-72** [comment]
Yes, I've make a screen capture to remember the angle.
No way uninstall "deeper" than the phone simple procedure for trying install it another time?

After that I've try this one, witch works but can't help me because it's very less accurate.
https://f-droid.org/fr/packages/uk.co.jarofgreen.JustADamnCompass/
Your app feel to be the other only one with no "anti-function".
and mechanical compass doesn't work very well to make a study of solar mask (it's what i what to do)

true that now F-Droid store say me the app is incompatible. I don't know why, I have android 6.0 and the only requirement i see in the app description is to have Android 5.1or newer. Is there any other requirement you send to this apps store witch can explain it's don't work?

**Comment by Kr0oked** [comment]
Yes there are other requirements besides the Android version. The app declares it needs the following features:

android.hardware.sensor.accelerometer
android.hardware.sensor.compass
android.hardware.sensor.gyroscope

App stores use these feature declerations to show if the app works on your device. Since the app cant access your devices sensor and the app store now says the app is incompatible it seems the problem is related to your devices sensors or the systems blocks accessing the sensors.

**Comment by MacAlan-72** [comment]
Okay.
So possible the problem comes from the accelerometer, because other apps works with compass and gyroscope.

Thanks you.

**Comment by Kr0oked** [comment]
Close issue due to inactivity
