### ISSUE TITLE
Nicer UI

### ISSUE THREAD

**Issue by inson1** [Kr0oked/Compass#52]
I think the name of the app and the icons on top of the page are too small.
And the compass is little bit too high.
What do you think?

![Screenshot_2023-10-16-07-29-46-521_com.bobek.compass.jpg](https://github.com/Kr0oked/Compass/assets/75314629/358990a5-5b53-4a5d-ae53-79c7f252927e)

**Comment by Kr0oked** [comment]
Regarding the name and icons I stick with the defaults from [Top app bar](https://m3.material.io/components/top-app-bar/specs#2be41d8e-79cf-4f1a-abc1-962744ca9291). That's also what I am used to from most other apps and what I would expect it to be here.

The position of the compass results from the alignment with the location area below.
![Bildschirmfoto vom 2023-10-21 16-25-25](https://github.com/Kr0oked/Compass/assets/5984532/d11e354b-5403-4132-a369-1fa4ff3ba3a7)

For me that alignments produces a harmonic result for most screen sizes and situations.

![Screenshot_20231021-162328](https://github.com/Kr0oked/Compass/assets/5984532/0363226f-f50e-42eb-b875-60ee828a3d0f)

In previous versions I tried to center the compass exactly at the devices screen. But since the app does not know how much space is taken by the system top bar and the app top bar that is not possible.
