### ISSUE TITLE
[DOCS] Add Translations (+Per-app language preferences) to Feature section in the Readme 

### ISSUE THREAD

**Issue by inson1** [Kr0oked/Compass#61]
I would add numbers of languages with translations (all types)

**Comment by Kr0oked** [comment]
Now with your PR I got your idea. But I would like to keep this description text as static as possible. Because  this description is contained in the README and all the translations. And I dont want to update all the files and the appstore texts (it's a manual process in Google Play) whenever the number of languages changes.

**Comment by inson1** [comment]
@Kr0oked okay I will delete that part of the PR
